# Generated by Django 6.0.2 on 2026-02-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Jewelry', 'Jewelry'), ("Men's Clothing", "Men's Clothing"), ("Women's Clothing", "Women's Clothing"), ('Liquor', 'Liquor'), ('Sale', 'Sale')], default='Electronics', max_length=100),
        ),
    ]
